export const CONST_REQUEST_STATUS_ENUM = {
  PENDING: "PENDING",
  TOPAY: "TOPAY",
  PROCESSING: "PROCESSING",
  TOCOMPLETE: "TOCOMPLETE",
  CLOSED: "CLOSED",
  CANCEL: "CANCEL",
  REJECTED: "REJECTED",
};

export const CONST_REQUEST_STATUS = [
  "PENDING",
  "TOPAY",
  "PROCESSING",
  "TOCOMPLETE",
  "CLOSED",
  "CANCEL",
  "REJECTED",
];

export const REQUEST_ERROR_NOT_FOUND = "Request type not found!";
  